version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3006:3006"
    environment:
      - TZ=Asia/Seoul
      - SERVER_IP=  # 서버 도메인 환경(https) 변수 설정
    #volumes:
    #  - ./frontend:/frontend
    restart: unless-stopped
