#version: '3.8'

services:
  frontend:
    container_name: k_radio_frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3006:3006"
    environment:
      - TZ=Asia/Seoul
      - HTTP_AUTH_ENABLED=false
      - HTTP_AUTH_USER=admin
      - HTTP_AUTH_PASS=password
      - SERVER_IP=${BACKEND_ADDRESS}
      - FRONTEND_PORT=${WEBUI_PORT}
    restart: unless-stopped
